### ISSUE TITLE
RuntimeError: CUDA error: unspecified launch failure

### ISSUE THREAD

**Issue by wjy3326** [v-iashin/BMT#16]
When I run video captioning from a raw video, I encounter this error. I use flask to put the feature extraction process and the caption generation process together to make a service. In order to release the memory in time, I use a multiprocessing method when extracting the features using vggish, but after extracting the features, I encounter the following error before generating the caption.
The error is here.

Using vanilla Generator
initialization: xavier
Glove emb of the same size as d_model_caps
Pretrained caption path: 
 pretrained_models/best_cap_model.pt
 * Serving Flask app "demo" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
i3d extraction time : 122.41406
i3d feature extraction is complete!
2021-01-16 13:44:56.115960: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2021-01-16 13:44:56.466762: E tensorflow/stream_executor/cuda/cuda_driver.cc:300] failed call to cuInit: CUDA_ERROR_NOT_INITIALIZED: initialization error
2021-01-16 13:44:56.466895: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] retrieving CUDA diagnostic information for host: localhost.localdomain
2021-01-16 13:44:56.466918: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:170] hostname: localhost.localdomain
2021-01-16 13:44:56.467077: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:194] libcuda reported version is: 390.25.0
2021-01-16 13:44:56.467163: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:198] kernel reported version is: 390.25.0
2021-01-16 13:44:56.467185: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:305] kernel version seems to match DSO: 390.25.0
Vggish feature extraction completed!
lens of the train_dataset: 1068
train_dataset.pad_idx 1
[2021-01-16 13:45:15,938] ERROR in app: Exception on /dense_video_caption [POST]
Traceback (most recent call last):
  File "/u01/isi/wangjunyan/envs/py36/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/u01/isi/wangjunyan/envs/py36/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/u01/isi/wangjunyan/envs/py36/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/u01/isi/wangjunyan/envs/py36/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/u01/isi/wangjunyan/envs/py36/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/u01/isi/wangjunyan/envs/py36/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "demo.py", line 418, in dense_video_caption
    prop_model, feature_paths, train_dataset.pad_idx, prop_cfg, args.device_id, args.duration_in_secs
  File "demo.py", line 230, in generate_proposals
    pad_feats_up_to=cfg.pad_feats_up_to
  File "demo.py", line 203, in load_features_from_npy
    stack_vggish = stack_vggish.to(torch.device(device)).unsqueeze(0)
RuntimeError: CUDA error: unspecified launch failure

the code to generate captions is as follows:

@app.route('/dense_video_caption', methods=['POST'])
def dense_video_caption():
    starttime = time.time()
    if request.method != "POST":
        return error("Only POST requests are expected!")
    if "file" not in request.files:
        return error("No filess found!")
    file = request.files['file']
    if not file:
        return error("No file found!")
    if file.filename == '':
        return error("No filename found!")
    if os.path.exists('upload'):
        subprocess.call('rm -rf upload', shell=True)
        subprocess.call('mkdir upload', shell=True)
    if os.path.exists(args.tmp_path):
        shutil.rmtree(args.tmp_path)
    filename = str(random.randint(0, 1000000)) + '.' + file.filename.rsplit('.', 1)[1]
    filename = os.path.join('upload', filename)
    file.save(filename)
    if not allowed_file(file.filename):  # 不是mp4文件，用ffmpeg转化成mp4文件
        basepath = 'upload'
        try:
            filename = fileProcessing(filename, basepath)
        except Exception as e:
            return error("Cannot read video file!")
   
    args.video_path = filename
    extract_feat(extractor_i3d, filename)
    time1 = time.time()
    print("i3d extraction time :", time1-starttime)
    print("i3d feature extraction is complete!")
    torch.cuda.empty_cache() 

    p = Process(target=extract_feat, args=(extractor_vgg, filename))
    p.start()
    if p.is_alive():
        p.join() 
    print("Vggish feature extraction completed!")

    filename_rgb = os.path.split(args.video_path)[-1].replace('.mp4', '_rgb.npy')
    filename_flow = os.path.split(args.video_path)[-1].replace('.mp4', '_flow.npy')
    filename_vggish = os.path.split(args.video_path)[-1].replace('.mp4', '_vggish.npy')
    # construct the paths to save the features
    args.rgb_features_path = os.path.join(args.output_path, filename_rgb)
    args.flow_features_path = os.path.join(args.output_path, filename_flow)
    args.vggish_features_path = os.path.join(args.output_path, filename_vggish)
    feature_paths = {
        'audio': args.vggish_features_path,
        'rgb': args.rgb_features_path,
        'flow': args.flow_features_path,
    }
    cap = cv2.VideoCapture(args.video_path)
    if cap.isOpened():  
        rate = cap.get(5)  
        FrameNumber = cap.get(7)  
        args.duration_in_secs = FrameNumber / rate   
    # Proposal
    print("lens of train_dataset: ", len(train_dataset))
    print("train_dataset.pad_idx", train_dataset.pad_idx)
    proposals = generate_proposals(
        prop_model, feature_paths, train_dataset.pad_idx, prop_cfg, args.device_id, args.duration_in_secs
    )
    # NMS if specified
    if args.nms_tiou_thresh is not None:
        proposals = non_max_suppresion(proposals.squeeze(), args.nms_tiou_thresh)
        proposals = proposals.unsqueeze(0)
    # Captions for each proposal
    captions = caption_proposals(
        cap_model, feature_paths, train_dataset, cap_cfg, args.device_id, proposals, args.duration_in_secs
    )
    result = {"result": captions, "time": time.time() - starttime}
    torch.cuda.empty_cache()  
    return result

**Comment by v-iashin** [comment]
Does the captioning work for raw video without Flask?

**Comment by wjy3326** [comment]
It can be run when extracting features and generating captions are processed separately. But when integrated with flask, if I don't use multiprocessing, I can run a service request only once, when the second service request is made, an exception will occur due to out of memory (maybe because vggish has extracted the features and did not release the memory) , so I added the vggish feature extraction process to a multiprocessing, but encounter the above error.

**Comment by v-iashin** [comment]
What do you want me to do?
