### ISSUE TITLE
Runtimeerror

### ISSUE THREAD

**Issue by shivani-2001** [v-iashin/BMT#21]
When i am running this command - 

python ./sample/single_video_prediction.py \
>     --prop_generator_model_path ./sample/best_prop_model.pt \
>     --pretrained_cap_model_path ./sample/best_cap_model.pt \
>     --vggish_features_path ./sample/women_long_jump_vggish.npy \
>     --rgb_features_path ./sample/women_long_jump_rgb.npy \
>     --flow_features_path ./sample/women_long_jump_flow.npy \
>     --duration_in_secs 35.155 \
>     --device_id 0 \
>     --max_prop_per_vid 100 \
>     --nms_tiou_thresh 0

I am facing this issue - File "./sample/single_video_prediction.py", line 279, in <module>
    cap_cfg, cap_model, train_dataset = load_cap_model(args.pretrained_cap_model_path, args.device_id)
  File "./sample/single_video_prediction.py", line 136, in load_cap_model
    train_dataset = ActivityNetCaptionsDataset(cfg, 'train', get_full_feat=False)
  File "/home/shivani/BMT/sample/../datasets/captioning_dataset.py", line 310, in __init__
    self.train_vocab, self.caption_loader = caption_iterator(cfg, self.batch_size, self.phase)
  File "/home/shivani/BMT/sample/../datasets/captioning_dataset.py", line 40, in caption_iterator
    CAPTION.build_vocab(dataset.caption, min_freq=cfg.min_freq_caps, vectors=cfg.word_emb_caps)
  File "/home/shivani/anaconda3/envs/bmt/lib/python3.7/site-packages/torchtext/data/field.py", line 273, in build_vocab
    self.vocab = self.vocab_cls(counter, specials=specials, **kwargs)
  File "/home/shivani/anaconda3/envs/bmt/lib/python3.7/site-packages/torchtext/vocab.py", line 88, in __init__
    self.load_vectors(vectors, unk_init=unk_init, cache=vectors_cache)
  File "/home/shivani/anaconda3/envs/bmt/lib/python3.7/site-packages/torchtext/vocab.py", line 147, in load_vectors
    vectors[idx] = pretrained_aliases[vector](**kwargs)
  File "/home/shivani/anaconda3/envs/bmt/lib/python3.7/site-packages/torchtext/vocab.py", line 401, in __init__
    super(GloVe, self).__init__(name, url=url, **kwargs)
  File "/home/shivani/anaconda3/envs/bmt/lib/python3.7/site-packages/torchtext/vocab.py", line 280, in __init__
    self.cache(name, cache, url=url, max_vectors=max_vectors)
  File "/home/shivani/anaconda3/envs/bmt/lib/python3.7/site-packages/torchtext/vocab.py", line 361, in cache
    dim))
RuntimeError: Vector for token b'Getatchew' has 10 dimensions, but previously read vectors have 300 dimensions. All vectors must have the same number of dimensions.

**And in i3d and vggish environment** 

python main.py \
>     --feature_type vggish \
>     --on_extraction save_numpy \
>     --device_ids 0 \
>     --video_paths ../../sample/women_long_jump.mp4 \
>     --output_path ../../sample/

this error is coming

home/shivani/anaconda3/envs/vggish/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/shivani/anaconda3/envs/vggish/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/shivani/anaconda3/envs/vggish/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/shivani/anaconda3/envs/vggish/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/shivani/anaconda3/envs/vggish/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/shivani/anaconda3/envs/vggish/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
usage: main.py [-h] [--train_meta_path TRAIN_META_PATH]
               [--val_1_meta_path VAL_1_META_PATH]
               [--val_2_meta_path VAL_2_META_PATH]
               [--modality {audio,video,audio_video}]
               [--video_feature_name VIDEO_FEATURE_NAME]
               [--audio_feature_name AUDIO_FEATURE_NAME]
               [--video_features_path VIDEO_FEATURES_PATH]
               [--audio_features_path AUDIO_FEATURES_PATH] [--d_vid D_VID]
               [--d_aud D_AUD] [--word_emb_caps WORD_EMB_CAPS]
               [--unfreeze_word_emb]
               [--feature_timespan_in_fps FEATURE_TIMESPAN_IN_FPS]
               [--fps_at_extraction FPS_AT_EXTRACTION]
               [--audio_feature_timespan AUDIO_FEATURE_TIMESPAN]
               [--train_json_path TRAIN_JSON_PATH] --procedure
               {train_cap,train_prop,evaluate}
               [--device_ids DEVICE_IDS [DEVICE_IDS ...]]
               [--start_token START_TOKEN] [--end_token END_TOKEN]
               [--pad_token PAD_TOKEN] [--max_len MAX_LEN]
               [--min_freq_caps MIN_FREQ_CAPS] [--optimizer {adam,sgd}]
               [--betas BETAS BETAS] [--eps EPS] [--momentum MOMENTUM]
               [--scheduler {constant,reduce_on_plateau}] [--lr LR]
               [--weight_decay WEIGHT_DECAY] [--lr_patience LR_PATIENCE]
               [--lr_reduce_factor LR_REDUCE_FACTOR] [--B B]
               [--inf_B_coeff INF_B_COEFF] [--epoch_num EPOCH_NUM]
               [--one_by_one_starts_at ONE_BY_ONE_STARTS_AT]
               [--early_stop_after EARLY_STOP_AFTER] [--smoothing SMOOTHING]
               [--grad_clip GRAD_CLIP]
               [--pretrained_prop_model_path PRETRAINED_PROP_MODEL_PATH]
               [--finetune_prop_encoder]
               [--pretrained_cap_model_path PRETRAINED_CAP_MODEL_PATH]
               [--finetune_cap_encoder] [--obj_coeff OBJ_COEFF]
               [--noobj_coeff NOOBJ_COEFF]
               [--pad_audio_feats_up_to PAD_AUDIO_FEATS_UP_TO]
               [--pad_video_feats_up_to PAD_VIDEO_FEATS_UP_TO]
               [--nms_tiou_thresh NMS_TIOU_THRESH] [--log_dir LOG_DIR]
               [--prop_pred_path PROP_PRED_PATH]
               [--avail_mp4_path AVAIL_MP4_PATH]
               [--reference_paths REFERENCE_PATHS [REFERENCE_PATHS ...]]
               [--tIoUs TIOUS [TIOUS ...]]
               [--max_prop_per_vid MAX_PROP_PER_VID]
               [--val_prop_meta_path VAL_PROP_META_PATH]
               [--model {transformer,av_transformer}] [--dout_p DOUT_P]
               [--N N] [--d_model D_MODEL] [--d_model_video D_MODEL_VIDEO]
               [--d_model_audio D_MODEL_AUDIO] [--d_model_caps D_MODEL_CAPS]
               [--use_linear_embedder] [--H H] [--d_ff_video D_FF_VIDEO]
               [--d_ff_audio D_FF_AUDIO] [--d_ff_caps D_FF_CAPS]
               [--anchors_num_video ANCHORS_NUM_VIDEO]
               [--anchors_num_audio ANCHORS_NUM_AUDIO]
               [--kernel_sizes_audio KERNEL_SIZES_AUDIO [KERNEL_SIZES_AUDIO ...]]
               [--kernel_sizes_video KERNEL_SIZES_VIDEO [KERNEL_SIZES_VIDEO ...]]
               [--conv_layers_audio [CONV_LAYERS_AUDIO [CONV_LAYERS_AUDIO ...]]]
               [--conv_layers_video [CONV_LAYERS_VIDEO [CONV_LAYERS_VIDEO ...]]]
               [--layer_norm] [--debug] [--dont_log]
main.py: error: the following arguments are required: --procedure

Please help me. I have downloaded all the packages. i am not getting how to resolve this.

**Comment by v-iashin** [comment]
> RuntimeError: Vector for token b'Getatchew' has 10 dimensions, but previously read vectors have 300 dimensions. All vectors must have the same number of dimensions.
Which version of `torchtext` are you using? (might be related to https://github.com/v-iashin/MDVC/issues/6)

> main.py: error: the following arguments are required: --procedure
Have you changed the directory to `submodules/video_features`?

**Comment by shivani-2001** [comment]
**torchtext==0.3.1**

(i3d) shivani@shivani-HP-Laptop-15-da0xxx:~/BMT/submodules/video_features$ python main.py     --feature_type i3d     --on_extraction save_numpy     --device_ids 0     --extraction_fps 25     --video_paths ../../sample/women_long_jump.mp4     --output_path ../../sample/
Saving features to ../../sample/
  0%|                                                                                                                                                                                | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
  File "main.py", line 73, in <module>
    parallel_feature_extraction(args)
  File "main.py", line 27, in parallel_feature_extraction
    replicas = torch.nn.parallel.replicate(extractor, args.device_ids[:len(indices)])
  File "/home/shivani/anaconda3/envs/i3d/lib/python3.7/site-packages/torch/nn/parallel/replicate.py", line 125, in replicate
    buffer_copies_not_rg = _broadcast_coalesced_reshape(buffers_not_rg, devices, detach=True)
  File "/home/shivani/anaconda3/envs/i3d/lib/python3.7/site-packages/torch/nn/parallel/replicate.py", line 89, in _broadcast_coalesced_reshape
    return comm.broadcast_coalesced(tensors, devices)
  File "/home/shivani/anaconda3/envs/i3d/lib/python3.7/site-packages/torch/cuda/comm.py", line 40, in broadcast_coalesced
    return torch._C._broadcast_coalesced(tensors, devices, buffer_size)
RuntimeError: CUDA error: no CUDA-capable device is detected (getDevice at /opt/conda/conda-bld/pytorch-nightly_1553749783957/work/c10/cuda/impl/CUDAGuardImpl.h:35)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x45 (0x7f630840f895 in /home/shivani/anaconda3/envs/i3d/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x1161d7 (0x7f630873f1d7 in /home/shivani/anaconda3/envs/i3d/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #2: <unknown function> + 0x5b1836 (0x7f6308bda836 in /home/shivani/anaconda3/envs/i3d/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #3: torch::cuda::broadcast_coalesced(c10::ArrayRef<at::Tensor>, c10::ArrayRef<long>, unsigned long) + 0x327 (0x7f6308bd8c37 in /home/shivani/anaconda3/envs/i3d/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x5b3f8e (0x7f6308bdcf8e in /home/shivani/anaconda3/envs/i3d/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0x127c06 (0x7f6308750c06 in /home/shivani/anaconda3/envs/i3d/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #28: __libc_start_main + 0xf3 (0x7f630d4810b3 in /lib/x86_64-linux-gnu/libc.so.6)

Exception ignored in: <function tqdm.__del__ at 0x7f62b1a92cb0>
Traceback (most recent call last):
  File "/home/shivani/anaconda3/envs/i3d/lib/python3.7/site-packages/tqdm/std.py", line 1086, in __del__
  File "/home/shivani/anaconda3/envs/i3d/lib/python3.7/site-packages/tqdm/std.py", line 1270, in close
  File "/home/shivani/anaconda3/envs/i3d/lib/python3.7/site-packages/tqdm/std.py", line 572, in _decr_instances
  File "/home/shivani/anaconda3/envs/i3d/lib/python3.7/site-packages/tqdm/_monitor.py", line 51, in exit
  File "/home/shivani/anaconda3/envs/i3d/lib/python3.7/threading.py", line 522, in set
  File "/home/shivani/anaconda3/envs/i3d/lib/python3.7/threading.py", line 365, in notify_all
  File "/home/shivani/anaconda3/envs/i3d/lib/python3.7/threading.py", line 348, in notify
TypeError: 'NoneType' object is not callable


(vggish) shivani@shivani-HP-Laptop-15-da0xxx:~/BMT/submodules/video_features$ python main.py \
>     --feature_type vggish \
>     --on_extraction save_numpy \
>     --device_ids 0 \
>     --video_paths ../../sample/women_long_jump.mp4 \
>     --output_path ../../sample/
Saving features to ../../sample/
/home/shivani/anaconda3/envs/vggish/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/shivani/anaconda3/envs/vggish/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/shivani/anaconda3/envs/vggish/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/shivani/anaconda3/envs/vggish/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/shivani/anaconda3/envs/vggish/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/shivani/anaconda3/envs/vggish/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

  0%|                                                                                                                                                                                | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
  File "main.py", line 73, in <module>
    parallel_feature_extraction(args)
  File "main.py", line 27, in parallel_feature_extraction
    replicas = torch.nn.parallel.replicate(extractor, args.device_ids[:len(indices)])
  File "/home/shivani/anaconda3/envs/vggish/lib/python3.7/site-packages/torch/nn/parallel/replicate.py", line 103, in replicate
    buffer_copies_not_rg = _broadcast_coalesced_reshape(buffers_not_rg, devices, detach=True)
  File "/home/shivani/anaconda3/envs/vggish/lib/python3.7/site-packages/torch/nn/parallel/replicate.py", line 67, in _broadcast_coalesced_reshape
    return comm.broadcast_coalesced(tensors, devices)
  File "/home/shivani/anaconda3/envs/vggish/lib/python3.7/site-packages/torch/nn/parallel/comm.py", line 56, in broadcast_coalesced
    return torch._C._broadcast_coalesced(tensors, devices, buffer_size)
RuntimeError: CUDA error: CUDA driver version is insufficient for CUDA runtime version
  0%|                                                                                                                                                                                | 0/1 [00:00<?, ?it/s]

(bmt) shivani@shivani-HP-Laptop-15-da0xxx:~/BMT$ python ./sample/single_video_prediction.py \
>     --prop_generator_model_path ./sample/best_prop_model.pt \
>     --pretrained_cap_model_path ./sample/best_cap_model.pt \
>     --vggish_features_path ./sample/women_long_jump_vggish.npy \
>     --rgb_features_path ./sample/women_long_jump_rgb.npy \
>     --flow_features_path ./sample/women_long_jump_flow.npy \
>     --duration_in_secs 35.155 \
>     --device_id 0 \
>     --max_prop_per_vid 100 \
>     --nms_tiou_thresh 0.4
Contructing caption_iterator for "train" phase
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉| 1567117/1567118 [02:13<00:00, 11700.82it/s]
Traceback (most recent call last):
  File "./sample/single_video_prediction.py", line 279, in <module>
    cap_cfg, cap_model, train_dataset = load_cap_model(args.pretrained_cap_model_path, args.device_id)
  File "./sample/single_video_prediction.py", line 136, in load_cap_model
    train_dataset = ActivityNetCaptionsDataset(cfg, 'train', get_full_feat=False)
  File "/home/shivani/BMT/sample/../datasets/captioning_dataset.py", line 310, in __init__
    self.train_vocab, self.caption_loader = caption_iterator(cfg, self.batch_size, self.phase)
  File "/home/shivani/BMT/sample/../datasets/captioning_dataset.py", line 40, in caption_iterator
    CAPTION.build_vocab(dataset.caption, min_freq=cfg.min_freq_caps, vectors=cfg.word_emb_caps)
  File "/home/shivani/anaconda3/envs/bmt/lib/python3.7/site-packages/torchtext/data/field.py", line 273, in build_vocab
    self.vocab = self.vocab_cls(counter, specials=specials, **kwargs)
  File "/home/shivani/anaconda3/envs/bmt/lib/python3.7/site-packages/torchtext/vocab.py", line 88, in __init__
    self.load_vectors(vectors, unk_init=unk_init, cache=vectors_cache)
  File "/home/shivani/anaconda3/envs/bmt/lib/python3.7/site-packages/torchtext/vocab.py", line 147, in load_vectors
    vectors[idx] = pretrained_aliases[vector](**kwargs)
  File "/home/shivani/anaconda3/envs/bmt/lib/python3.7/site-packages/torchtext/vocab.py", line 401, in __init__
    super(GloVe, self).__init__(name, url=url, **kwargs)
  File "/home/shivani/anaconda3/envs/bmt/lib/python3.7/site-packages/torchtext/vocab.py", line 280, in __init__
    self.cache(name, cache, url=url, max_vectors=max_vectors)
  File "/home/shivani/anaconda3/envs/bmt/lib/python3.7/site-packages/torchtext/vocab.py", line 361, in cache
    dim))
RuntimeError: Vector for token b'Getatchew' has 10 dimensions, but previously read vectors have 300 dimensions. All vectors must have the same number of dimensions.

**Comment by shivani-2001** [comment]
I don't know what is happening with this code but every time when i try to fix something it gives some new error
(i3d) shivani@shivani-HP-Laptop-15-da0xxx:~/BMT/submodules/video_features$ python main.py \
>     --feature_type i3d \
>     --on_extraction save_numpy \
>     --device_ids 0 \
>     --extraction_fps 25 \
>     --video_paths ../../sample/women_long_jump.mp4 \
>     --output_path ../../sample/
Saving features to ../../sample/
Traceback (most recent call last):
  File "main.py", line 73, in <module>
    parallel_feature_extraction(args)
  File "main.py", line 12, in parallel_feature_extraction
    from models.i3d.extract_i3d import ExtractI3D  # defined here to avoid import errors
  File "/home/shivani/BMT/submodules/video_features/models/i3d/extract_i3d.py", line 13, in <module>
    from models.i3d.flow_src.pwc_net import PWCNet
  File "/home/shivani/BMT/submodules/video_features/models/i3d/flow_src/pwc_net.py", line 8, in <module>
    import models.i3d.flow_src.correlation as correlation
  File "/home/shivani/BMT/submodules/video_features/models/i3d/flow_src/correlation.py", line 7, in <module>
    import cupy
ModuleNotFoundError: No module named 'cupy'

(vggish) shivani@shivani-HP-Laptop-15-da0xxx:~/BMT/submodules/video_features$ python main.py \
>     --feature_type vggish \
>     --on_extraction save_numpy \
>     --device_ids 0 \
>     --video_paths ../../sample/women_long_jump.mp4 \
>     --output_path ../../sample/
Saving features to ../../sample/
2021-02-12 01:22:39.448854: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-02-12 01:22:39.448891: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "main.py", line 73, in <module>
    parallel_feature_extraction(args)
  File "main.py", line 15, in parallel_feature_extraction
    from models.vggish.extract_vggish import ExtractVGGish  # defined here to avoid import errors
  File "/home/shivani/BMT/submodules/video_features/models/vggish/extract_vggish.py", line 12, in <module>
    from models.vggish.vggish_src import (vggish_input, vggish_params,
  File "/home/shivani/BMT/submodules/video_features/models/vggish/vggish_src/vggish_slim.py", line 36, in <module>
    slim = tf.contrib.slim
AttributeError: module 'tensorflow' has no attribute 'contrib'


(bmt) shivani@shivani-HP-Laptop-15-da0xxx:~/BMT$ python ./sample/single_video_prediction.py \
>     --prop_generator_model_path ./sample/best_prop_model.pt \
>     --pretrained_cap_model_path ./sample/best_cap_model.pt \
>     --vggish_features_path ./sample/women_long_jump_vggish.npy \
>     --rgb_features_path ./sample/women_long_jump_rgb.npy \
>     --flow_features_path ./sample/women_long_jump_flow.npy \
>     --duration_in_secs 35.155 \
>     --device_id 0 \
>     --max_prop_per_vid 100 \
>     --nms_tiou_thresh 0.4
2021-02-12 01:22:54.702989: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-02-12 01:22:54.703018: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Contructing caption_iterator for "train" phase
Traceback (most recent call last):
  File "./sample/single_video_prediction.py", line 279, in <module>
    cap_cfg, cap_model, train_dataset = load_cap_model(args.pretrained_cap_model_path, args.device_id)
  File "./sample/single_video_prediction.py", line 136, in load_cap_model
    train_dataset = ActivityNetCaptionsDataset(cfg, 'train', get_full_feat=False)
  File "/home/shivani/BMT/sample/../datasets/captioning_dataset.py", line 310, in __init__
    self.train_vocab, self.caption_loader = caption_iterator(cfg, self.batch_size, self.phase)
  File "/home/shivani/BMT/sample/../datasets/captioning_dataset.py", line 13, in caption_iterator
    spacy_en = spacy.load('en')
  File "/home/shivani/anaconda3/lib/python3.8/site-packages/spacy/__init__.py", line 47, in load
    return util.load_model(name, disable=disable, exclude=exclude, config=config)
  File "/home/shivani/anaconda3/lib/python3.8/site-packages/spacy/util.py", line 328, in load_model
    raise IOError(Errors.E941.format(name=name, full=OLD_MODEL_SHORTCUTS[name]))
OSError: [E941] Can't find model 'en'. It looks like you're trying to load a model from a shortcut, which is deprecated as of spaCy v3.0. To load the model, use its full name instead:

nlp = spacy.load("en_core_web_sm")

For more details on the available models, see the models directory: https://spacy.io/models. If you want to create a blank model, use spacy.blank: nlp = spacy.blank("en")

**Comment by v-iashin** [comment]
```
# install spacy language model. Make sure you activated the conda environment
python -m spacy download en
```

Have you done this?

`conda list cupy`

What does it return?

`conda list tensorflow`

What does it return?

`$ nvidia-smi`

What does it return?

**Comment by v-iashin** [comment]
Which OS are you using? Is it Windows?

**Comment by shivani-2001** [comment]
> Which OS are you using? Is it Windows?

No, i am running on ubuntu

**Comment by shivani-2001** [comment]
> ```
> # install spacy language model. Make sure you activated the conda environment
> python -m spacy download en
> ```
>  Installed 

> Have you done this?
> 
> `conda list cupy`

>cupy                      8.4.0                    pypi_0    pypi
cupy-cuda111              8.4.0                    pypi_0    pypi
cupy-cuda80               7.8.0                    pypi_0    pypi
 
> What does it return?
> 
> `conda list tensorflow`

> tensorflow                1.13.1          gpu_py37hc158e3b_0    anaconda
tensorflow-base           1.13.1          gpu_py37h8d69cac_0    anaconda
tensorflow-estimator      1.13.0                     py_0    anaconda
tensorflow-gpu            1.13.1               h0d30ee6_0    anaconda

> What does it return?
> 
> `$ nvidia-smi`

>sudo apt install nvidia-340               # version 340.108-0ubuntu5.20.04.1, or
sudo apt install nvidia-utils-390         # version 390.141-0ubuntu0.20.04.1
sudo apt install nvidia-utils-450         # version 450.102.04-0ubuntu0.20.04.1
sudo apt install nvidia-utils-450-server  # version 450.102.04-0ubuntu0.20.04.1
sudo apt install nvidia-utils-460         # version 460.32.03-0ubuntu0.20.04.1
sudo apt install nvidia-utils-435         # version 435.21-0ubuntu7
sudo apt install nvidia-utils-440         # version 440.82+really.440.64-0ubuntu6
sudo apt install nvidia-utils-418-server  # version 418.181.07-0ubuntu0.20.04.1
 
> What does it return?

**Comment by v-iashin** [comment]
> cupy 8.4.0 pypi_0 pypi
> cupy-cuda111 8.4.0 pypi_0 pypi
> cupy-cuda80 7.8.0 pypi_0 pypi

Please install the correct version:
https://github.com/v-iashin/video_features/blob/4fa02bd5c5b8c34081dcfb609e2bcd5a973eaab2/conda_env_i3d.yml#L16

>tensorflow 1.13.1 gpu_py37hc158e3b_0 anaconda
> tensorflow-base 1.13.1 gpu_py37h8d69cac_0 anaconda
> tensorflow-estimator 1.13.0 py_0 anaconda
> tensorflow-gpu 1.13.1 h0d30ee6_0 anaconda

Well, I am not sure why it cannot find `tf.contrib` which is present in `1.13.1` and was removed in TF 2.0. Also, `libcudart.so.11.0` in your errors suggests that you have CUDA 11.0 and TF 1.13.1 is compiled with CUDA 10 (https://www.tensorflow.org/install/source#gpu). You can checkout how to install different cuda in your environment by googling for `conda install cudatoolkit=<version>`

Please fix your tensorflow version or Cuda version or both I don't know.

> OSError: [E941] Can't find model 'en'. It looks like you're trying to load a model from a shortcut, which is deprecated as of spaCy v3.0.

Which version of `spacy` are you using? I guess it is `>=3.0` but the version in the provided code is lower than this. 

https://github.com/v-iashin/BMT/blob/3418fdf2c94d6df42971dd592c08529cad6f7d1d/conda_env.yml#L66

> Command 'nvidia-smi' not found, but can be installed with:

Do you realize that this code is designed to run on an Nvidia GPU? It seems that you don't have it or the drivers are not installed. 

So, you cannot install the environment properly, you don't have a GPU/drivers and you are blaming the code for failing. What do you expect me to do? I know that some people got it running somehow. 

Is it such a big deal to run?
```
conda env create -f ./conda_env.yml
cd submodules/video_features
conda env create -f ./conda_env_i3d.yml
conda env create -f ./conda_env_vggish.yml
```

Since it is the problem with your environment, I am going to close this one for now. If you disagree or I am missing something from your inconsistent and overwhelming errors feel free to let me know.

**Comment by ArionMiles** [comment]
>Do you realize that this code is designed to run on an Nvidia GPU? It seems that you don't have it or the drivers are not installed.

I'm trying to run this inside WSL on Ubuntu 18.04. Do we need to install GPU drivers separately?

Because I've run this:
```
conda env create -f ./conda_env.yml
cd submodules/video_features
conda env create -f ./conda_env_i3d.yml
conda env create -f ./conda_env_vggish.yml
```

and when I try to run I3D feature extraction in the `i3d` conda env, I run into a problem with CuPy which says:

`ImportError: libcuda.so.1: cannot open shared object file: No such file or directory`
and 
`ImportError: CuPy is not correctly installed.`

I had assumed that the `cudatoolkit=10.0.130=0` installed by conda (for video_features) would install all necessary software. Clearly I'm doing something wrong. Since the ReadMe didn't mention anything about GPU driver installation, I overlooked that.

**Comment by ArionMiles** [comment]
So, I got a VM with GPU drivers preinstalled online (Squarespace) and was able to run the single video prediction flow. It works well!

The issue was with GPU drivers on my WSL local machine.

Great work with the code and paper! 
Cheers!

**Comment by v-iashin** [comment]
Hi, I am glad you found your way around this.

Nvidia GPU is the de-facto standard in the deep learning world, not only in research. I think it goes without saying that you have a GPU with drivers installed. I doubt that it will be useful to add in README as anyone who ever tried to run any DL-library code on a GPU is aware of this.
