### ISSUE TITLE
RuntimeError: Vector for token b'27ll' has 38 dimensions, but previously read vectors have 300 dimensions

### ISSUE THREAD

**Issue by xanthan011** [v-iashin/BMT#34]
Hello Vladimir,

I'm trying to run your repository on **Google Colab** and I'm facing this error which I hope you can address it and give me some insight on the same.

 I even have read your readme file but I'm trying to replicate the instructions mentioned in [this article](https://towardsdatascience.com/dense-video-captioning-using-pytorch-392ca0d6971a) 

So when I'm trying to run this command after activating the _bmt_ environment:

```
python ./sample/single_video_prediction.py \
    --prop_generator_model_path /content/BMT/sample/best_prop_model.pt \
    --pretrained_cap_model_path /content/BMT/best_cap_model.pt.1  \
    --vggish_features_path /content/BMT/test/y2mate_vggish.npy \
    --rgb_features_path /content/BMT/test/y2mate_rgb.npy \
    --flow_features_path /content/BMT/test/y2mate_flow.npy \
    --duration_in_secs 99 \
    --device_id 0 \
    --max_prop_per_vid 100 \
    --nms_tiou_thresh 0.4
```

This error shows up:
```
Contructing caption_iterator for "train" phase
100%|█████████▉| 753786/753787 [01:21<00:00, 9194.76it/s]
Traceback (most recent call last):
  File "./sample/single_video_prediction.py", line 279, in <module>
    cap_cfg, cap_model, train_dataset = load_cap_model(args.pretrained_cap_model_path, args.device_id)
  File "./sample/single_video_prediction.py", line 136, in load_cap_model
    train_dataset = ActivityNetCaptionsDataset(cfg, 'train', get_full_feat=False)
  File "/content/BMT/sample/../datasets/captioning_dataset.py", line 310, in __init__
    self.train_vocab, self.caption_loader = caption_iterator(cfg, self.batch_size, self.phase)
  File "/content/BMT/sample/../datasets/captioning_dataset.py", line 40, in caption_iterator
    CAPTION.build_vocab(dataset.caption, min_freq=cfg.min_freq_caps, vectors=cfg.word_emb_caps)
  File "/usr/local/envs/bmt/lib/python3.7/site-packages/torchtext/data/field.py", line 273, in build_vocab
    self.vocab = self.vocab_cls(counter, specials=specials, **kwargs)
  File "/usr/local/envs/bmt/lib/python3.7/site-packages/torchtext/vocab.py", line 88, in __init__
    self.load_vectors(vectors, unk_init=unk_init, cache=vectors_cache)
  File "/usr/local/envs/bmt/lib/python3.7/site-packages/torchtext/vocab.py", line 147, in load_vectors
    vectors[idx] = pretrained_aliases[vector](**kwargs)
  File "/usr/local/envs/bmt/lib/python3.7/site-packages/torchtext/vocab.py", line 401, in __init__
    super(GloVe, self).__init__(name, url=url, **kwargs)
  File "/usr/local/envs/bmt/lib/python3.7/site-packages/torchtext/vocab.py", line 280, in __init__
    self.cache(name, cache, url=url, max_vectors=max_vectors)
  File "/usr/local/envs/bmt/lib/python3.7/site-packages/torchtext/vocab.py", line 361, in cache
    dim))
RuntimeError: Vector for token b'27ll' has 38 dimensions, but previously read vectors have 300 dimensions. All vectors must have the same number of dimensions.
```

I'm not sure why this issue is coming and I have tried everything in my power to solve it. 

For reproducing this issue, here is the [colab file](https://colab.research.google.com/drive/1DruayAC-ymCabfr4qfxt67iqJre61Bti?usp=sharing). You can run it and reproduce the issue . Just to be clear, many improvisations had to be done after following the article to run this repository, but I'm stuck at the very last step and I hope you can help me. 

I have also attached a video while on which we are running, you can directly upload it in test folder and you wouldn't have to change any paths.

https://user-images.githubusercontent.com/69425158/130767285-b58d4aca-0ee4-4007-9e0f-2bad4c5008b8.mp4

**Comment by v-iashin** [comment]
Hi, @xanthan011 

Thanks for submitting the issue. 

Google Colab environment is not supported. I decided to check it out because I have seen this error before in #21 that was troublesome to debug without a mwe which, admittedly, you provided. However, again, there is nothing wrong with this code, it is a problem with the environment you are trying to use.

Anyway, the main problem is the lack of disk space on Google Colab. When you run https://github.com/v-iashin/BMT/blob/d45ad8f11d35bc7d1757ac1d735952384b4fa4c1/datasets/captioning_dataset.py#L40
it unpacks the pre-trained glove zip which expands dramatically in size + `torchtext` resaves it (2.1G -> 5.3G + 2.6G). Since there is no disk space, only a part of the file is saved on the disk. Google Colab shows no error and continues execution.

You need to remove something to fix it. 

1. I removed the second captioning checkpoint (`best_cap_model.pt.1`) which you are mistakingly downloading for the second time.
2. I removed the extracted features as you don't need these for the single video example. These features are downloaded and unpacked in https://github.com/v-iashin/BMT/blob/d45ad8f11d35bc7d1757ac1d735952384b4fa4c1/download_data.sh#L1-L62
```bash
%%bash
rm -r /content/BMT/data/i3d_25fps_stack64step64_2stream_npy
```
3. Run `conda clean --all` after installing conda environments because conda caches library tarballs after installing packages which allocate lots of space usually. After doing so step 2 should be optional.

There is another error in your code:
```bash
conda install -c conda-forge spacy
python -m spacy download en
```
Likely, it does not do what you expect it to do. The `python` here is aliased with the Colab's internal default Python library, not conda's so you are installing the language model there. Plus, `spacy` is already installed in the `bmt` environment – you only need to install the language model. You can do it as follows instead
```
%%bash
source activate bmt
/usr/local/envs/bmt/bin/python -m spacy download en
```

I managed to run the notebook after these fixes on `./sample/women_long_jump.mp4`. 

I am planning to add a Google Colab notebook to the repo which will support the single video example. If you want to author a PR, please create a `.ipynb` notebook and I will merge it. If you will decide to do so, please clean and reorganize your current version a bit.

---

> I'm trying to replicate the instructions mentioned in this article
>Just to be clear, many improvisations had to be done after following the article to run this repository, but I'm stuck at the very last step and I hope you can help me.

Just to be clear, I didn't write this article you need to improvise upon but I wrote the paper and released this code which that article uses. By the way, I checked your colab file and there is no evidence of the improvisation. It just copies stuff from the README.md which I provided already and tries to stick it to the Google Colab environment.

> I EVEN have read your readme file

This is cute!

You need to understand that this code was not designed to run in Google Colab but you are still trying to run it there and ask for my help. I don't have to help you here and even release this repo to the public. Please be polite not only in how you write but also to others' time. Just because you did not manage to debug _your_ work properly, right now you are asking me to do it which shows exactly the opposite.

**Comment by xanthan011** [comment]
Hello Vladimir,

Firstly, thank your for the response. 
 

> Google Colab environment is not supported. I decided to check it out because I have seen this error before in #21 that was troublesome to debug without a mwe which, admittedly, you provided. However, again, there is nothing wrong with this code, it is a problem with the environment you are trying to use.

yes, I knew this before I created a colab file, but on my local machine cuda isn't supported, so I had no choice.

> it unpacks the pre-trained glove zip which expands dramatically in size + torchtext resaves it (2.1G -> 5.3G + 2.6G). Since there is no disk space, only a part of the file is saved on the disk. Google Colab shows no error and continues execution. I'm wondering if having Colab Pro would help in this case. Please give your thoughts

So, even I had a 60% guess that this might be the issue as colab did throw a warning saying that the disk is full and I wasn't able to locate the .vector_cache folder.

> I removed the second captioning checkpoint (best_cap_model.pt.1) which you are mistakingly downloading for the second time.

Actually this wasn't a mistake. Somehow the best_cap_model.pt file was getting corrupted when I ran the last cell. It threw an error `eof expected or corrupt file` . Idk why but I thought the best solution was to replace it by downloading a new one.

> Just to be clear, I didn't write this article you need to improvise upon but I wrote the paper and released this code which that article uses. By the way, I checked your colab file and there is no evidence of the improvisation. It just copies stuff from the README.md which I provided already and tries to stick it to the Google Colab environment.

I totally understand. I saw the author of the article beforehand. The only reason to mention the article so that you might have an idea why the structure of the notebook is different than your readme and by improvisation, I meant in the structure of the code and few minor bits here and there. Nothing new that will contribute.

> You need to understand that this code was not designed to run in Google Colab but you are still trying to run it there and ask for my help. I don't have to help you here and even release this repo to the public. Please be polite not only in how you write but also to others' time. Just because you did not manage to debug your work properly, right now you are asking me to do it which shows exactly the opposite.


Firstly, I have the utmost respect of the time you and every developer out there who provides the code for their papers. I never indented to waste your time as I already knew that probably there nothing was wrong with the code, but I was really stuck so I thought its worth mentioning as only one similar issue #21 was there. Secondly, I mentioned that I read your readme so that you have an idea that I have gone through your explanation of the code and tried everything else present there.

 Thirdly, somehow github exaggerated by line, it was suppose to be this: 

> I even have read your readme file

but somehow it capitalized the word to make it look dramatic. 😂. But anyways, I have respect of your time and I appreciate that you took some time to go through my problem. 

I hope now there is no misunderstanding. I understand your duty only extends till solving the errors to the specifications and conditions you provide in which the code will work, and as a developer myself, I respect that

> I am planning to add a Google Colab notebook to the repo which will support the single video example. If you want to author a PR, please create a .ipynb notebook and I will merge it. If you will decide to do so, please clean and reorganize your current version a bit. 

If I'm able to make this notebook run successfully then sure, I would love to contribute back, after all the effort is all yours.

**Comment by v-iashin** [comment]
>somehow it capitalized the word

I capitalized the word to point out what bothered me there.
