### ISSUE TITLE
meteor  error

### ISSUE THREAD

**Issue by duola1970** [v-iashin/BMT#7]
During the caption evaluation, the following error occurred, please tell me how to solve it, thank you！

Traceback (most recent call last):
  File "/home/njj/niu/video-caption-project/BMT/TMT-project/evaluation/meteor_test.py", line 36, in <module>
    val_metrics = calculate_metrics(reference_paths, submission_path, tIoUs, 100)
  File "/home/njj/niu/video-caption-project/BMT/TMT-project/evaluation/meteor_test.py", line 12, in calculate_metrics
    max_prop_per_vid, PREDICTION_FIELDS, verbose, only_proposals)
  File "/home/njj/niu/video-caption-project/BMT/TMT-project/evaluation/evaluate.py", line 64, in __init__
    (Meteor(), "METEOR"),
  File "/home/njj/niu/video-caption-project/BMT/TMT-project/submodules/pycocoevalcap/meteor/meteor.py", line 25, in __init__
    stderr=subprocess.PIPE)
  File "/home/njj/anaconda3/envs/mdvc/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/home/njj/anaconda3/envs/mdvc/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'java': 'java'
Exception ignored in: <function Meteor.__del__ at 0x7f8d33e3e950>
Traceback (most recent call last):
  File "/home/njj/niu/video-caption-project/BMT/TMT-project/submodules/pycocoevalcap/meteor/meteor.py", line 79, in __del__
    self.lock.acquire()
AttributeError: 'Meteor' object has no attribute 'lock'

Process finished with exit code 1

**Comment by v-iashin** [comment]
Haven't had java huh? By the way, the conda environment has `openjdk` 🙂
